resources:
- check-feasibility-api-service.yaml
- check-feasibility-api-deployment.yaml

commonLabels:
  app: s4air-check-feasibility-api

namePrefix:
  s4air-check-feasibility-api-

configMapGenerator:
- name: config
  env: config.properties

generatorOptions:
 disableNameSuffixHash: true
